version: '3.1'

services:

  # web: # nginx
  # app_server: # app_server
  # app_subscriber: # app_subscriber

  mysql_database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 53306:3306

  postgres_database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 55432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  redis_database:
    image: redis
    ports:
      - 56379:6379
    volumes:
      - redis-volume:/data

volumes:
  mysql-volume:
  redis-volume:
  postgres-volume:
